#postgre connection
spring.datasource.url=jdbc:postgresql://brubgfyw:uJ2Ce7AuP-CzdD6gwJPQnxtZ0z58lkm1@rain.db.elephantsql.com/brubgfyw
spring.datasource.username=brubgfyw
spring.datasource.password=uJ2Ce7AuP-CzdD6gwJPQnxtZ0z58lkm1
spring.datasource.driver-class-name=org.postgresql.Driver