#postgre connection
spring.datasource.url=jdbc:postgresql://rain.db.elephantsql.com:5432/brubgfyw
spring.datasource.username=brubgfyw
spring.datasource.password=uJ2Ce7AuP-CzdD6gwJPQnxtZ0z58lkm1
spring.datasource.driverClassName=org.postgresql.Driver
spring.session.jdbc.initialize-schema: always